# Generated by Django 3.1.3 on 2024-09-03 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_replycomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replycomment',
            old_name='replyment',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_comments', to='pybo.comment'),
        ),
        migrations.AddField(
            model_name='replycomment',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pybo.answer'),
        ),
        migrations.AddField(
            model_name='replycomment',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pybo.question'),
        ),
    ]
