# Generated by Django 3.1.3 on 2024-09-04 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_auto_20240903_1906'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReplyComment',
        ),
    ]
